name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate Gradle Wrapper (Version 8.7)
        run: gradle wrapper --gradle-version 8.7

      - name: Patch Manifest and Layout Errors
        run: |
          # 1. جایگزینی آیکون با فایل موجود و حذف راند آیکون
          sed -i 's/@mipmap\/ic_launcher/@drawable\/logo3/g' app/src/main/AndroidManifest.xml
          sed -i '/android:roundIcon/d' app/src/main/AndroidManifest.xml
          
          # 2. اصلاح غلط تایپی در فایل لایه‌بندی
          sed -i 's/android:A_height/android:layout_height/g' app/src/main/res/layout/activity_main.xml

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload Debug APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TMAS-Debug-APK
          path: app/build/outputs/apk/debug/*.apk
